//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public Equipo()
        {
            this.Partido = new HashSet<Partido>();
            this.Partido1 = new HashSet<Partido>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Partido> Partido { get; set; }
        public virtual ICollection<Partido> Partido1 { get; set; }
        public virtual TablaPosiciones TablaPosiciones { get; set; }
    }
}
