//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaPosiciones
    {
        public int Id { get; set; }
        public short PG { get; set; }
        public short PE { get; set; }
        public short PP { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
