//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloAuditoriias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        public Proceso()
        {
            this.Actividad = new HashSet<Actividad>();
        }
    
        public int IdProceso { get; set; }
        public string Nombre { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual ICollection<Actividad> Actividad { get; set; }
    }
}
