//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronMan.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participantes
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Estado { get; set; }
        public string Numero { get; set; }
        public string Domicilio_Calle { get; set; }
        public short Domicilio_Numero { get; set; }
        public string Domicilio_Piso { get; set; }
        public short Domicilio_Departamento { get; set; }
        public string Domicilio_Cuidad { get; set; }
        public string Domicilio_Provincia { get; set; }
        public string Domicilio_Pais { get; set; }
        public int Prueba_Id { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Pruebas Pruebas { get; set; }
    }
}
