//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronMan.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pruebas
    {
        public Pruebas()
        {
            this.Participantes = new HashSet<Participantes>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Distancia { get; set; }
        public int Evento_Id { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual ICollection<Participantes> Participantes { get; set; }
    }
}
